//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AjoEntities : DbContext
    {
        public AjoEntities()
            : base("name=AjoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cor_customer> cor_customer { get; set; }
        public virtual DbSet<cor_sub_admin> cor_sub_admin { get; set; }
        public virtual DbSet<cor_sub_admin_login_log> cor_sub_admin_login_log { get; set; }
        public virtual DbSet<cor_super_admin> cor_super_admin { get; set; }
        public virtual DbSet<cor_super_admin_login_log> cor_super_admin_login_log { get; set; }
        public virtual DbSet<cor_transactions> cor_transactions { get; set; }
    }
}
