//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cor_transactions
    {
        public long TransactionId { get; set; }
        public long CustomerId { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> AmountContributed { get; set; }
        public Nullable<decimal> AmountCollected { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> AmountPayable { get; set; }
        public Nullable<decimal> Debt { get; set; }
        public Nullable<decimal> TotalDebt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
