//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cor_sub_admin_login_log
    {
        public long LogId { get; set; }
        public long SubId { get; set; }
        public string FullName { get; set; }
        public System.DateTime LoginDate { get; set; }
    }
}
